#version 430 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer Pos {
	vec4 position[];
};

layout(std430, binding = 1) buffer Dir {
	vec4 velocity[];
};

layout(std430, binding = 2) buffer Col {
	vec4 colors[];
};

uniform vec2 cursorPos;
uniform float deltaTime;

uniform vec2 windowSize;

float acc = 0.3;

void main() {
	uint idx = gl_GlobalInvocationID.x;

	vec3 p = position[idx].xyz;
	vec3 v = velocity[idx].xyz;

	vec3 direction = normalize(vec3(cursorPos, 0.0) - p);

	v += direction * acc;
	v *= 0.98;

	// Update the position based on the velocity (momentum)
	p += v;

	// Store updated velocity and position
	velocity[idx].xyz = v;
	position[idx].xyz = p;

	float speed = clamp(length(v) * 30, 0.1, 1.0);
	vec3 particleColor = vec3(0.0, speed, 1.0);

	// Store the color for this particle
//	colors[idx].xyz = particleColor;

	// Reflect particles when they hit the boundaries
	if (p.x > windowSize.x / 2.0 || p.x < -(windowSize.x / 2.0)) {
		velocity[idx].xy = reflect(velocity[idx].xy, vec2(1.0, 0.0));
	}
	if (p.y > windowSize.y / 2.0 || p.y < -(windowSize.y / 2.0)) {
		velocity[idx].xy = reflect(velocity[idx].xy, vec2(0.0, 1.0));
	}
}
